services:
  - type: web
    name: icca-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_7gOSZ0desNAz@ep-dawn-lab-adocbyur-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: JWT_SECRET
        value: icca-secure-jwt-secret-2024-change-this
      - key: RESEND_API_KEY
        value: re_8oNk18Td_GMMu1tieZAz12zGsdonitHPz
      - key: CORS_ORIGINS
        value: https://quiet-beijinho-a5ff63.netlify.app