services:
  - type: web
    name: icca-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_7gOSZ0desNAz@ep-dawn-lab-adocbyur-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: RESEND_API_KEY
        value: re_8oNk18Td_GMMu1tieZAz12zGsdonitHPz
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://icca-frontend.vercel.app,http://localhost:5173